### ISSUE TITLE
rememberme cookie path

### ISSUE THREAD

**Issue by markleary** [getgrav/grav-plugin-login#102]
Rememberme was not working correctly on my site, because the cookie path was being set to a subdirectory (the url path where users mostly commonly login) rather then the root of the site.  The issue seems to be on line 423 of Controller.php:

`$cookie->setPath($this->grav['base_url_relative']);`

In my instance, $this->grav['base_url_relative'] returns ''.  I'm not sure, but this my be related to a closed grav core bug:

https://github.com/getgrav/grav/issues/868

I resolved this by setting $cookie->setPath('/') but that does not seem like a reliable fix.

**Comment by flaviocopes** [comment]
It probably needs to be 

`$cookie->setPath($this->grav['base_url_relative'] ?: '/');`

so it uses the value of base_url_relative if Grav runs in a subfolder, or `/` if not.

**Comment by rhukster** [comment]
Fixed for next release.
