### ISSUE TITLE
Configurable group/roles as part of user registration 

### ISSUE THREAD

**Issue by anthubbard** [getgrav/grav-plugin-login#103]
Hi ppl,

I'd love to have the ability to have a user select the group / role they will be a part of during the registration process. So part of the registration form for a grav user login, they would be able to select the group / role from a range of checkbox's or radio buttons.

**Comment by flaviocopes** [comment]
Doable: customize the registration form https://github.com/getgrav/grav-plugin-login#customizing-the-registration-form 

Copy the `register_user` action from https://github.com/getgrav/grav-plugin-login/blob/develop/login.php#L679 and add the logic to process the additional ACL assigned to each user.
