### ISSUE TITLE
Documentation on custom login unclear

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav-plugin-login#104]
> Alternatively, you can also provide a specific login route if you wish to forward users to a specific login page. To do this you need to create a copy of the login.yaml from the plugin in your user/config/plugins folder and provide a specific route (or just edit the plugin setttings in the admin plugin).

Create a copy and put it where, exactly?

**Comment by flaviocopes** [comment]
Copy https://github.com/getgrav/grav-plugin-login/blob/develop/login.yaml and put it in `user/config/plugins/login.yaml`

The same can be done simply saving the Login plugin configuration via Admin

**Comment by matthew-dean** [comment]
> The same can be done simply saving the Login plugin configuration via Admin

In the admin UI, there isn't any configuration for the login plugin...?

**Comment by flaviocopes** [comment]
You should see it under **Plugins -> Login**

![screen shot 2017-02-13 at 19 53 53](https://cloud.githubusercontent.com/assets/11783388/22898066/39f97934-f226-11e6-8405-149407ac9d47.png)

**Comment by matthew-dean** [comment]
> Copy https://github.com/getgrav/grav-plugin-login/blob/develop/login.yaml and put it in user/config/plugins/login.yaml

This has no effect. Any changes made to the login.yaml file in `user/config/plugins/login.yaml` does not change settings for the login plugin.

**Comment by flaviocopes** [comment]
Do you happen to have an environment-specific config? https://learn.getgrav.org/advanced/environment-config
