### ISSUE TITLE
Protected pages and ACL-Rules

### ISSUE THREAD

**Issue by axelf** [getgrav/grav-plugin-login#106]
Hi,

in the documentation i read the following: 
Admin: Gives the user access to the Grav Admin back end. This role does not include front end access to protected pages.

Why can i write in the page header 
`access:
    admin.login: true
`
if admin means, there is no access to protected pages?

**Comment by flaviocopes** [comment]
`admin.*` is by convention used just in Admin. Frontend ACL should start with `site.*`. No fixed rule, just a convention. And the Login plugin only protects pages with `site.login` added to them.
