### ISSUE TITLE
Store the current account in a blueprint

### ISSUE THREAD

**Issue by fbab** [getgrav/grav-plugin-login#107]
Dear all,

I want to store in the frontmatter the name of the current account logged with the help of grav-plugin-login.

I tried the following "config-default@: grav.user.username" in user/themes/antimatter/blueprints/item.yaml but the Author field remains empty.

Do you see any other hint ?

Thanks for your help, FBA.

Excerpt : user/themes/antimatter/blueprints/item.yaml

```yaml
title: Item
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        blog:
          type: tab
          title: Blog Item

          fields:

            header.content.author:
              type: text
              # yaml: true
              label: Author
              # default: 'John DEFAULT'
              config-default@: grav.user.username
'''

**Comment by flaviocopes** [comment]
You cannot do this with `config-default@` as it looks in the Grav configuration, not in the Grav object. You can lookup properties in `user/config` in that way.

Instead, you can use `data-default@`:

```yaml
              data-default@: '\Grav\Plugin\Login\Login::username'
```

And in `user/plugins/login/Login.php`

```php
    public static function username() {
        return Grav::instance()['user']->username;
    }
```

This method does not exist, it's just an example. You can pick this sample and add your own small plugin to provide it.

**Comment by fbab** [comment]
Thx for your reply.
Thank to your indication, I initiatied a fork of auto-update at : https://github.com/fbab/grav-plugin-auto-date.
Bye.
