### ISSUE TITLE
Reset password hash / salt 

### ISSUE THREAD

**Issue by ArrowBaZ** [getgrav/grav-plugin-login#108]
Hello,

I think there is a mistake with reset procedure

https://github.com/getgrav/grav-plugin-login/blob/develop/classes/Controller.php#L242

```
$password = isset($data['password']) ? $data['password'] : null;
$user->password = $password;
```

New password is set from data (provied by form input, not hash / salt by grav)
and password strengh isn't check not in reset.md and procedure to reset
and `unset($user->hashed_password); unset($user->reset);` doesn't remove this field in account files.

Maybe I miss something ?

Regards,
Arrowbaz

**Comment by rhukster** [comment]
Just tested this. Reset password works fine.  Password is hashed after you have entered the new password.
