### ISSUE TITLE
Not working with Receptar theme

### ISSUE THREAD

**Issue by zasmth** [getgrav/grav-plugin-login#109]
Trying to protect the entire site with the login theme, applying it to the home page, but the appearance is getting messed up and is buggy. I can still click things I shouldn't be able to.

Here's a screenshot of the strange appearance: http://i.imgur.com/OTTy37r.png

https://github.com/getgrav/grav-theme-receptar

Issues experience on a fresh install, literally nothing else has been changed.

**Comment by flaviocopes** [comment]
The plugin is generally intended to be used on a site that has some pages under a private area, the Receptar theme might not have your use case covered, and some links still appear. 

This is a case where a stock theme cannot really provide what you need, and you need to create a child theme https://learn.getgrav.org/themes/customization#theme-inheritance and edit the Twig files as you want.
