### ISSUE TITLE
What's the expected behaviour of 'protect_protected_page_media'?

### ISSUE THREAD

**Issue by elliotlewis** [getgrav/grav-plugin-login#111]
I have a page with login required:

```
access:
    site.login: true
```
The login.yaml has:

```
protect_protected_page_media: true
```

This page has an image, location: `http://localhost/user/pages/01.home/image.png`.

If I try to access this image while logged out, I can still view it.

I was expecting `protect_protected_page_media` to require login to view this image?

**Comment by rhukster** [comment]
That does seem like it should work. I'll take a look.

**Comment by flaviocopes** [comment]
Is this only happening on your home page (accessed at `/`), or also to other pages of the site?

**Comment by elliotlewis** [comment]
This wasn't on the home page, so I've tested there. Still doesn't work.

I've also tried on a sub-page and set `parent_acl: true`. The sub-page does *not* have `site.login: true` but the login form appears as expected. I can access the media on the sub-page as well, so does not work as expected.

It doesn't appear to work for any page media.

It looks like `function authorizeFallBackUrl()` is handling this restriction, but I can't find how this method is called?

**Comment by flaviocopes** [comment]
Replicated the problem, there seem to be some bit missing in handling the 403

**Comment by rhukster** [comment]
Ok, test this and here's the deal.

When you access an image by it's physical path, ie, `http://localhost/user/pages/01.home/image.png`, the web server is actually serving that file directly.  Grav is not in the picture at all, and is not able to protect that image.

However, if you access the file via the page route: `http://localhost/home/image.png` or `http://localhost/image.png`, this is where Grav is involved, and is actually finding the image and streaming it.  This is where the `protect_protected_page_media: true` option comes into play.

I have confirmed this does protect the image linked by page route and prompts for login as expected.

**Comment by Aisbergg** [comment]
I want to serve all content through PHP and block direct access from my webserver (Nginx) so I can enforce the authorization. Thing is, Grav seems to create absolute paths for images as default so `![](images/myimg.png)` will become `/user/pages/images/myimg.png`. For other files like text-files for example `[restricted-file](restricted.txt)` it does generate the correct page route `/de/intern/restricted.txt"`. 
My question is, is there an option to let Grav generate the page route for images instead of absolute paths? Otherwise the Login-Plugin can't do it's job properly.

**Comment by rhukster** [comment]
The problem is when you access an image (like `myimg.png`) the browser is expecting a image, so you can't simply redirect that image request to an HTML page, all we can really do is a 404 or something the browser can interpret but still does not serve the image.

**Comment by aligator** [comment]
I use this now:
(Nginx)
````
location /user/pages/ {
    rewrite ^/user/pages/(.*)Intern/Galerie/(.*)/(.*)$ /intern/galerie/$2/$3 redirect;
}
````

You can adapt it to your needs.
it redirects all directly called files to the internal route.

For apache something similar should work, too. Can someone try it with apache?

**Comment by rhukster** [comment]
I have not been able to come up with a satisfactory solution to this other than doing something like you are doing with rewrite rules...
