### ISSUE TITLE
Site-wide require login? [FR]

### ISSUE THREAD

**Issue by elliotlewis** [getgrav/grav-plugin-login#112]
Feature request: It would be good to require login of every page by adding the below to `site.yaml` rather than each pages frontmatter. Is this already possible?

```
access:
    site.login: true
```

**Comment by rhukster** [comment]
That doesn't exist as it stands.  For sitewide access it's probalby better to use a basic auth security via your webserver.  The alternative is to use the maintenance plugin and customize the error/landing page.  This basically does what you are asking for.
