### ISSUE TITLE
parent_acl: true, cannot load js which is on the partials

### ISSUE THREAD

**Issue by GMusliaj** [getgrav/grav-plugin-login#116]
When parent_acl: true, and I am logged in the js files are not loaded for a given partial, check the partial below:

```
<link rel="stylesheet" href="/user/themes/learn2/file.css">
<style type="text/css">.removed { display: none; }</style>
<script src="/user/themes/learn2/file1.js"></script>
<div id="body-inner">
<h1>{{ page.title }}</h1>
<p>
	{{ page.content }}
</p>
<script src="/user/themes/learn2/file2.js"></script>
</div>
```

/user/themes/learn2/file1.js and /user/themes/learn2/file2.js are not loaded even if I am authenticated. Disabled parent_acl and everything was loaded and working as expected.

**Comment by flaviocopes** [comment]
Please provide all we need to replicate the issue. Are you using the Learn2 theme, but you customized it? As it has no file1.js or file2.js files by default. Attach all the other relevant things  (page structure)

**Comment by rhukster** [comment]
Closed due to inactivity
