### ISSUE TITLE
Cannot change passwd via CLI

### ISSUE THREAD

**Issue by idotobi** [getgrav/grav-plugin-login#119]
When I try changing the password of one of my accounts I get the following Error:

    $ bin/plugin login passwd
    Changing User Password
    
    Enter a username: admin
    PHP Fatal error:  Class 'Grav\Plugin\Console\Grav' not found in /var/www/html/mysite.net/user/plugins/logi/cli/ChangePasswordCommand.php on line 135

 - I'm runing an up-to-date Debian GNU/Linux 8 (jessie)
 - My php version is `PHP 5.6.30`
 - the login plugin is up-to-date

       $ bin/gpm info login
       
       GPM Releases Configuration: Stable
       
       Found package 'login' under the 'Plugins' section
       
       Login [login]
       -------------
       Enables user authentication and login screen.
       
       Author      : Team Grav <devs@getgrav.org> <http://getgrav.org>
       Version     : 2.3.1

Apart from that, thanks for a great plugin!

**Comment by flaviocopes** [comment]
Thanks for reporting, looks like a bug introduced between Grav `1.2.4` and `1.3.0-rc.1`

**Comment by idotobi** [comment]
Thanks for fixing 👍

**Comment by idotobi** [comment]
The patch you did was already present in my version.

For me the following change in `user/plugin/login/cli/ChangePasswordCommand.php` resolved the problem:

```diff
@@ -1,6 +1,7 @@
 <?php
 namespace Grav\Plugin\Console;
 
+use Grav\Common\Grav;
 use Grav\Console\ConsoleCommand;
 use Grav\Common\File\CompiledYamlFile;
 use Grav\Common\User\User;
```
