### ISSUE TITLE
Remember Me is not needed.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav-plugin-login#121]
It seems to me that one can still access a private page after the browser is closed, when he has been authenticated without the Remember Me checkbox checked.

To reproduce this:
1 set up a private page, and an account to access that page;
2 try browse to that page, and enter the credentials; do NOT check Remember Me though. Then log in;
3 now we are on the private page; close the whole browser (that is, rather than just the browser tab);
4 try browse to that page again, and I go directly to the page, without having to enter the credentials. I suppose I still need to enter the credentials, since I did not enable "Remember Me".

**Comment by flaviocopes** [comment]
"Remember me" simply stores the authentication in a persistent cookie, which can last months, rather than using the default session duration time. It has nothing to do with closing the browser. To be logged out, either you don't log in to the site for 30 minutes (default configuration) or you clear the browser cookies.

**Comment by hifall** [comment]
So you are not using session cookies then, which is different than the behavior of some other login systems.

**Comment by flaviocopes** [comment]
It does, but it sets the session expire value, which prevents the cookies from clearing if the browser closes. This PR I just made https://github.com/getgrav/grav/pull/1538 allows to set 0 as the timeout value (previously impossible), which will cause the clear of the session when the browser closes (unless browser features interfere, like described in https://stackoverflow.com/a/10772420/205039). Feel free to test it.

**Comment by hifall** [comment]
A quick test shows I am still able to go directly to the target page. That is, no behavior difference after I applied the change in the PR.

**Comment by flaviocopes** [comment]
Which browser are you using? I tested Safari and the setting was respected. Chrome did not.

**Comment by hifall** [comment]
I used the latest Firefox.

**Comment by hifall** [comment]
Did a test on Safari 10.0, and the behavior is the same as what I got in Firefox.

**Comment by flaviocopes** [comment]
Are you testing Admin? Admin has its own session timeout configuration setting.

**Comment by flaviocopes** [comment]
You need to set that to 0 as well, in admin.yaml (or in the Admin plugin config, in Admin itself - and logout / login again)

**Comment by hifall** [comment]
No, I think I am just testing the regular user.

**Comment by flaviocopes** [comment]
Do you actually have `0` in the session timeout configuration in `user/config/system.yaml`?

**Comment by hifall** [comment]
Hmm, I did not. Maybe that's what was missing. I will try to add that later and let you know.

**Comment by flaviocopes** [comment]
Ok, the session will reset on browser close only if that value is set to 0. Let me know when you test.

**Comment by hifall** [comment]
Yup, it works! Now Remember Me flag is respected!

**Comment by hifall** [comment]
BTW, it seems to me Grav should either: set session.timeout=0 in system.yaml when login/Remember Me is enabled, or at least document this behavior.
