### ISSUE TITLE
Custom permissions.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav-plugin-login#122]
In additional to existing permissions like site.login, etc, can I define arbitrary permissions?

For example, I'd like to define a permission in groups.yaml like:
access:
    custom:
        permission: true

Then require a page has permission custom.permission like:
access:
    custom.permission: true

Is this possible?

Thanks!

**Comment by Vivalldi** [comment]
Yes you can use custom permissions.

```
access:
  custom:
    permission: true
```

and

```
access:
  custom.permission: true
```
