### ISSUE TITLE
Login Error: Can't read account files -- permission denied

### ISSUE THREAD

**Issue by JoshuaPaceIntl** [getgrav/grav-plugin-login#123]
I recently set up Grav CMS with multiple users and I used the changepass CLI function to change their passwords to something more secure. However, after making this change, I am getting the following error for all accounts:

````
Failed to read username.yaml: Opening file for writing failed on error fopen(/var/www/html/sitename/cache//compiled/files/[hashstring].yaml.php): failed to open stream: Permission denied
````

I was able to log in to two of these accounts prior to attempting the password change. Since then, I have chown'd and chmod'd the user account config files to no avail.

**Comment by Vivalldi** [comment]
Have you ensured that the user PHP is running as has proper permissions?

https://learn.getgrav.org/troubleshooting/permissions

**Comment by JoshuaPaceIntl** [comment]
I cleared the cache files and now the logins are working again.
