### ISSUE TITLE
Maintenance plugin with multiple languages

### ISSUE THREAD

**Issue by juanfcocontreras** [getgrav/grav-plugin-login#124]
If I'm right maintenance plugin uses login plugin to login users. My website is multilanguage and my home url is like:

http://server/app

If I try to login in that url everything works as expected.

Nevertheless, if I stay at the site without doing anything, I'm logged out and I have to login again. In that case the url is changed to the following ones according to the language I selected in the web:

http://server/app/en
http://server/app/es

In those urls, no matter I input right credentials, I'm always prompt to login again.

Is that ok?

Sorry in advance if the issue is no login plugin related. I'm not totally sure.

**Comment by juanfcocontreras** [comment]
It is solved by changing in file `login-form.html.twig` of maintenance plugin the line:

`<form method="post" action="{{ base_url_relative ~ uri.path }}">`

by:

`<form method="post" action="{{ base_url_relative }}">`

So I think I should be post the issue there. Please close this issue.

**Comment by rhukster** [comment]
This is not really a solid solution for all situations.  When you don't use a custom login page, and the login form is displayed on the secured page you are trying to access, using `page.url` actually breaks things. 

This seems to be an issue specifically with the maintenance plugin issue with multi-languages.  If your page.url solution works, then use that :)
