### ISSUE TITLE
using "_" in routes generates errors in grav.log

### ISSUE THREAD

**Issue by LaurentOngaro** [getgrav/grav-plugin-login#125]
Hi,
I've noticed that using "_" by "-" in routes generates errors in grav.log

The best solution is to replace "_" by "-" in all routes uses by the plugin
It must be done in the plugin's sources files and its config files.

BR

**Comment by flaviocopes** [comment]
Hi, can you tell me how to replicate the problem, exactly? Thanks!

**Comment by LaurentOngaro** [comment]
Hi,
I've just made a fresh install of grav, with a few plugins and some customizations for a multilangual site (french, english).
This is the kind of error I'm talking about
`[2017-07-13 09:17:07] grav.NOTICE: Invalid slug set in YAML frontmatter:  => user_register [] []`

I've tested in on my dev blog, at http://dev.gamecoderblog.com

Each time I acces to the http://dev.gamecoderblog.com/user_register page, an error is logged, _but the plugin runs well and the user is registered._

If you want, I can send you the whole sources of this installation, and send you the admin access, but not very hot to put that on this public issue page.
Perhaps we can proceed by mail or PM ?

**Comment by flaviocopes** [comment]
So you have `route_register: /user_register` in the Login plugin configuration. I don't have issues with this.

Could this a problem unrelated to this, and instead be an issue in your pages? Did you set the slug in one of your pages?

**Comment by LaurentOngaro** [comment]
In the case of my dev blog, all the settings are those used by default (I have no login.yaml files in the user/config folder).

> Could this a problem unrelated to this, and instead be an issue in your pages? Did you set the slug in one of your pages?

I don't thing so, because, as I said, the setup for this test blog is a basic one:  latest GRAV version, 6 plugins, nearly all settings by default, but some specific settings in system.yaml (2 languages, windows specific settings...)

You can contact me on my mail, laurent@AT@gamecoderblog.com, as it I could send you the whole test site.

**Comment by rhukster** [comment]
Technically speaking routes are slugs and slugs by definition should be alphanumeric separated by dashes: https://en.wikipedia.org/wiki/Semantic_URL#Slug

**Comment by LaurentOngaro** [comment]
yes, I agree with Andy , I've also noticed the same kind of errors when I was using a slug that contains some uppercase, for instance "project-Cpp" was generating this error, but "project-cpp" no.

**Comment by rhukster** [comment]
BTW, this debug statement was removed in 1.3.0
