### ISSUE TITLE
custom login page

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav-plugin-login#126]
(cross posted in Grav forum, but code references at end)
In Login plugin documentation, a custom login page is possible if in `user/config/plugins/login.yaml` 
there is the line 
```
route: /user-login
```
I added to `user/config/plugins/login.yaml` the line
``` 
route: /newLogin
``` 
to login.yaml.

I created a file `newLogin.md` based on `login.md` in login/pages with only a couple of extra words to differentiate between the new and default.  
I have been unable to get Grav to recognise `newLogin.md` in any location.  

I have a single page where in the front matter, access: site.login: true is set, namely for `<mysite>/events`  
As soon as a user tries to access the page, login is invoked - good.  
But only the default login page is triggered - bad  

I have put `newLogin.md` in all of the following directories:
```
user/plugins/login/pages/
user/pages/
user/pages/events/
user/pages/en-gb/
```

My site uses multiple languages, in particular: en-gb, zh-cn, zh-hk
I have therefore put `newLogin.en-gb.md` in the following directories:
```
user/plugins/login/pages/
user/pages/
user/pages/events/
```
None of these work. In each case the default login page is triggered.
Is this my error (not putting newLogin in the right place) or a bug?

To verify whether this was a language bug, I tried on a completely new site with only English. I still could not get it to work.

It seems to me that this is a bug. It appears that in login.php, around line 227, $page is False.

**Comment by rhukster** [comment]
The route is the page folder, so you really should call your route something like:

```
route: `/new-login`
```

In the `user/config/plugins/login.yaml` file. This means that if you now go to `http://yoursite.com/new-login` you should see the default login form.  

Now if you actually create a page called `user/pages/new-login/login.md` and then in that page put something like:

```
login
```

You should see this new form... I've just tested this and it works fine.
