### ISSUE TITLE
Error latest login develop --> breaks login

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-login#128]
Just installed latest login plugin develop, result:

![error](https://user-images.githubusercontent.com/12480617/30034927-eeef4058-91a4-11e7-9ca3-0b0f1bacf42a.png)

Before this I also installed latest grav/admin develop.

**Update: breaks login and site!**

**Comment by rhukster** [comment]
We're in the middle of a refactor of login plugin with new events so it looks like the problem is there.  I think you need the latest released toolbox also, so do a composer update.

**Comment by rhukster** [comment]
BTW, i rolled login back so it doesn't require this update to toolbox.  However, the next verison will have it.
