### ISSUE TITLE
Login error should not trigger an error page

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-plugin-login#13]
I mistyped my password while trying to login to the backoffice but instead of the simple error message _Login failed_ added to the original login page I got this full error page:

>> 0.
>> …/­system/­src/­Grav/­Common/­Twig/­Twig.php300

>> Whoops \ Exception \ ErrorException (E_ERROR)

> Call to a member function content() on a non-object
> Open: /srv/data/web/vhosts/reachcontent.com/htdocs/system/src/Grav/Common/Twig/Twig.php
> 
>          */
>         public function processSite($format = null)
>         {
>             // set the page now its been processed
>             $this->grav->fireEvent('onTwigSiteVariables');
>             $pages = $this->grav['pages'];
>             $page = $this->grav['page'];
>             $content = $page->content();
>             $config = $this->grav['config'];
>      
> 
> GET Data empty
> POST Data
> username 	***[correct login used]***
> password 	***[wrong password typed; displayed in clear]***
> task 	login
> admin-nonce 	$2y$10$fHaePQnnA37EbUSLASHMyKeUrOhfMJxcjCbiJwefZSLASHSgtMsxLzsWPDc6K
> Files empty
> Cookies
> grav-site-360e8fa-admin 	na964dfl6opnql30fb8a3oc7q0
> Session
> user 	Grav\Common\User\User Object ( [gettersVariable:protected] => items [items:protected] => Array ( ) [blueprints:protected] => [storage:protected] => )
> expert 	
> messages 	RocketTheme\Toolbox\Session\Message Object ( [messages:protected] => Array ( > [5ab00046cc2b8a920d69eba0a5350300] => Array ( [message] => Login failed [scope] => error ) ) )
> Server/Request Data
> USER 	hosting-user
> HOME 	/
> FCGI_ROLE 	RESPONDER
> REDIRECT_STATUS 	200
> etc. etc.

**Comment by reachcontent** [comment]
All plugins were up to date, except for Login, but nothing changed after updating it to latest (1.0.1), logging out then trying to log in with an erroneous password.
Reloading the page gave the expected result of the proper login page with error message 'Login failed' in red.

**Comment by flaviocopes** [comment]
Strange, not sure why is that happening, never happened to me! The `Login failed` message is what I usuall get. Was the Grav cache cleared after updating the plugin? Can you still recreate it now?

**Comment by reachcontent** [comment]
Clearing the cache (both _All cache_ thru Admin, and with the _cache cleaning plugin_, which I guess performs exactly the same command) doesn't change a thing.
I reproduced it on a Chrome browser also since my Firefox configuration is quite custom.
Seems I need to reload twice to get to the proper login page with error message.

**Comment by flaviocopes** [comment]
Can you zip your `user/` folder and send it to me via a Gitter PM? I need to recreate it to see what's the problem

**Comment by reachcontent** [comment]
Ok, done although I'm new to Gitter so I created a room to share the archive.
reachcontent/Login-issue3

**Comment by flaviocopes** [comment]
Discussed in the room, could be related to the hosting setup and caching, closing this for now
