### ISSUE TITLE
Google OAuth not working after Update

### ISSUE THREAD

**Issue by jorgemfm** [getgrav/grav-plugin-login#130]
I had google OAuth working, but after I update from Grav 1.3.1 to 1.3.3 it no longer works.
I Check the configuration and everything appears to be OK

Before:
![grav_oauth_before](https://user-images.githubusercontent.com/1022369/30323837-ac9ae21c-97b6-11e7-8513-daff2a183dff.PNG)

After:
![grav_oauth_after](https://user-images.githubusercontent.com/1022369/30323839-b02298f8-97b6-11e7-97b0-2219b84f4456.PNG)

PS: Don't know if its an issue with grav-plugin-login or with grav-plugin-login-oauth so i've created the issue in both, please delete as you see fit. Thank you

**Comment by rhukster** [comment]
This should be sorted with 2.4.1 of Login + 1.3.1 of Login-Oauth plugins.. They should show up in GPM within the hour.

**Comment by jorgemfm** [comment]
Problem solved with update.

Thank you!
