### ISSUE TITLE
Register form breaks when a custom form is added

### ISSUE THREAD

**Issue by jackween** [getgrav/grav-plugin-login#135]
When I download the newest Grav admin + default Antimatter theme, enable the Register page for the Login plugin, and also create a “form.md” page of my own (with a form), the Register page’s Submit button fails to function. Instead, it just refreshes the page without creating a user as you would expect. If I remove the “form” information from my form.md’s frontmatter, the Register page properly creates a user.

The example form I followed:
https://learn.getgrav.org/forms/forms/example-form

I have found a workaround. In `user\plugins\form\form.php` on the line immediately below

`list($forms, $flat_forms) = $this->grav['cache']->fetch($cache_id);`

I added `$forms = array();`. What features am I losing by adding this code to my site? I need registration to work.

**Comment by rhukster** [comment]
I just found that there was a missing event in the core grav: https://github.com/getgrav/grav/commit/1ca61818569d7b1fff2955d4742e604fe5483de1

This was causing the login-plugin-provided pages to not work properly.  Along with that the example in the docs was bad for the register.  It should of had a message and a reset.  Anyway, i've tested both internal registration page, and a custom one, and both are working.  Make sure you have lowercase username as there is some HTML5 form validation happening, and I had 1password on which was hiding the error when i typed a username with a capital letter.

**Comment by jackween** [comment]
Awesome! I'm really fond of Grav, so I appreciate your efforts.
