### ISSUE TITLE
How to access the login page directly?

### ISSUE THREAD

**Issue by shoorlyne** [getgrav/grav-plugin-login#138]
I understand once a page is protected, the visitor will be redirected to the login page before he can access it.

But how would one access the login page directly? I'd like to put up a Log In link on my grav page, so that when one clicks that link, the login page shows up.

**Comment by rhukster** [comment]
Just define a route for the login page in the login configuration and it will be available on that page.

**Comment by shoorlyne** [comment]
It works. Thanks!
