### ISSUE TITLE
Submitting user registration information silently rejects creation of new user

### ISSUE THREAD

**Issue by frans-fuerst** [getgrav/grav-plugin-login#139]
**Observation**: after filling out the user registration form and pressing "submit" the site is being reloaded - fields are empty - and no user has been created (no new .yaml file in user/accounts folder). There is no error message (not in logs, console, debug messages or on form itself)
Registering a new user using `bin/plugin login newuser` works.

**Expectation**: new user with given credentials gets created or error messages being provided on form or in `logs/grav.log` 

Versions in use: Grav 1.3.8, login plugin 2.4.3

**Comment by Vivalldi** [comment]
Hello @frans-fuerst! 

Thank you for this well outlined report. I am having issues replicating the issue. What does your `login.yaml` look like?

**Comment by rhukster** [comment]
I think you need to clear the cache.

**Comment by frans-fuerst** [comment]
That was the first thing for me to try but without any effect - I do also clear the cache every time when starting my grav server.
Is there a way to get more detailed logging output?

**Comment by frans-fuerst** [comment]
Here are my `login.yaml` files  - had to rename them because GitHub does not like YAML
[user_config_plugins_login.yaml.txt](https://github.com/getgrav/grav-plugin-login/files/1521619/user_config_plugins_login.yaml.txt)
[user_plugins_login_login.yaml.txt](https://github.com/getgrav/grav-plugin-login/files/1521620/user_plugins_login_login.yaml.txt)

**Comment by Vivalldi** [comment]
Alright! So it seems to do with the `login_after_registration` setting. When `false` it would seem that it simply doesn't create the user. I'll look into this.

**Comment by frans-fuerst** [comment]
setting `login_after_registration` to `true` doesn't help in my case. Even reverting all settings to default (and clearing the cache) has no effect.

**Comment by rhukster** [comment]
OK i can replicate with the built-in registration form.  Have been using a custom registration form for so long I never noticed.  Will look into this now as i've been working on some major "login" plugin updates in the past couple of days.

**Comment by Vivalldi** [comment]
@frans-fuerst I was able to replicate the behavior and now after fiddling around I can't seem to duplicate. I'll get back to you.

**Comment by rhukster** [comment]
I know the problem, and have already fixed it locally.  I'm doing quite a major refactor of both login and form plugin to clean things up and optimize them.  The form was not being processed properly in this case with a dynamic page.  With my own page it was fine.  I'm trying to clean up the whole processing logic to handle dynamically added pages better.

**Comment by frans-fuerst** [comment]
sounds great! is there a workaround for this behavior (apart from registering everyone on CLI)?

**Comment by rhukster** [comment]
The workaround is to create a your own `profile` page and not rely on the built-in one.  Documentation on this is in the README.md

Fixed in develop anyway, hope to have this release out either over the weekend or monday latest.

**Comment by frans-fuerst** [comment]
A quick try on v2.5.0 seems to work for me!

**Comment by rhukster** [comment]
Nice!

**Comment by pjkaufman** [comment]
I am running into the same issue as described above on version 3.0.2. I am trying to register new users, but no user file is being created in the user/accounts folder. I have not been able to find any errors related to the  registration in `logs/grav.log`. I am curious if this should still be occurring?
here is my login.yaml file: 
[login.yaml.txt](https://github.com/getgrav/grav-plugin-login/files/3336064/login.yaml.txt)
