### ISSUE TITLE
Update changelog somewhere

### ISSUE THREAD

**Issue by HugoGresse** [getgrav/grav-plugin-login#14]
Since reace 1.0, CHANGELOG.md is not updated and GitHub release did not contains the change

**Comment by flaviocopes** [comment]
This should be the problem https://github.com/getgrav/grav-plugin-login/commit/428491546cb8a0972f9381727797301500c224f3, should be fixed

**Comment by HugoGresse** [comment]
there are differences between changelog version and GitHub release too.
