### ISSUE TITLE
Ability to enable session for Admin only

### ISSUE THREAD

**Issue by MakaryGo** [getgrav/grav-plugin-login#140]
Possible enchancement:
As session is by default split for front and admin, there could be a setting to enable session for Admin only. Thus we could serve front pages without any cookies.

**Comment by PatTheMav** [comment]
This would be very helpful as the current state makes frontend caching e.g. via Nginx a pain, as Nginx can't conditionally hide the `Set-Cookie` header in responses and thus session cookies become part of cached static pages.
