### ISSUE TITLE
Markdown Not Processed On User Profile Page

### ISSUE THREAD

**Issue by catchlight** [getgrav/grav-plugin-login#141]
Not sure if this is an issue with the plugin or with Grav, but for some reason markdown is not being processed on user/plugins/login/pages/profile.md as indicated by the H1 tag in my screenshot.

Any ideas about this?

![profile-page](https://user-images.githubusercontent.com/1256376/34184774-2ce7d7e0-e4e7-11e7-8c52-a3daca709749.png)

**Comment by catchlight** [comment]
Found the fix digging through some of the other templates. I changed `{{ page.content }}` to `{{ content|raw }}` in user/plugins/login/templates/profile.html.twig

**Comment by Vivalldi** [comment]
Would you be able to create a pull request?

If not I'll be able to get to it later this week.

**Comment by rhukster** [comment]
This should totally work now, just use markdown in your profile page.
