### ISSUE TITLE
custom site access by group permissions is not working

### ISSUE THREAD

**Issue by cesarmarinhorj** [getgrav/grav-plugin-login#145]
this works, ok...
access:
  site.login: true

but the custom permission dont. it show me the page for the user that dont has those permissions in my page, of type default.
access:
  site.login: true
  custom.second: true

I have three groups:
default, premium, full
those groups is sharing the permissions:
in default:
access:
  custom:
    first: true
    second: false
    third: false

in premium:
access:
  custom:
    first: true
    second: true
    third: false

thanks

**Comment by cesarmarinhorj** [comment]
in page template, this works...
{% if grav.user.authorize('custom.first') %}
here is the first
{% endif %}

{% if grav.user.authorize('custom.second') %}
here is the second
{% endif %}

**Comment by cesarmarinhorj** [comment]
I changed to simplify things.
instead:

in premium:
access:
custom:
first: true
second: true
third: false

changed to:

in premium:
access:
custom:
second: true

and works!
just site.login: true
and grav.user.authorize in template.

**Comment by rhukster** [comment]
In the future please paste your YAML between triple back ticks so it keeps the YAML format.  It's basically unusable without it.
