### ISSUE TITLE
Initialize Session if deferred

### ISSUE THREAD

**Issue by AliveDevil** [getgrav/grav-plugin-login#148]
There has been the addition of `system.session.initialize` in https://github.com/getgrav/grav/commit/e217489d37b917f9a7931fd551498cdd88eae9e5#diff-48620dcdb527e8c73c7f3288cb92675b which would allow https://github.com/getgrav/grav-plugin-login/issues/140 to be resolved.

I'd like to see login-plugin to initialize session on login not initializeSession.
Possible implementation requires modification of https://github.com/getgrav/grav-plugin-login/blob/develop/login.php#L932-L933.

Current behavior of disabled `system.session.initialize` is a non-working login despite adding `$session->init()` to mentioned lines above.

**Comment by mahagr** [comment]
You cannot just initialize session on login as the session is needed both before login (token) and after login (next request). Basically, I'm handling this by initializing my custom session before Login:

```php
    /**
     * [onPluginsInitialized:10001] Override session handler before login plugin calls it.
     */
    public function initializeSession()
    {
        if ($this->grav['config']->get('system.session.initialize', 1)) {
            throw new \RuntimeException('Please change system.session.initialize to false');
        }

        $this->grav['session'] = new MySession(); // Extends Grav\Common\Session
        $this->grav['session']->init();
    }
```
