### ISSUE TITLE
`login.css` loaded while not showing login page

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-login#153]
When `core + admin` packages are installed, `login.css` is displayed on front-end pages.

Is this stylesheet really needed when no login page is shown?

**Comment by rhukster** [comment]
As you can have your own custom login pages pretty much anywhere in a Grav site, the CSS needs to be ready and available.  However it's not very large, and you can simply copy this into your own css and modify as needed, then disable the built-in css via the plugin config.
