### ISSUE TITLE
add-user ignores desired username

### ISSUE THREAD

**Issue by SimJoSt** [getgrav/grav-plugin-login#157]
I created a new user using `bin/plugin login add-user` and entered a username when prompted.
After entering all the other information as well, I got the following success message
> Success! User 1 created.

I thought nothing of it, as I just created 1 (one) user. But appearently the user was actually named `1`. I had to change the name of the `.yml` file in the `accounts` folder.

**Comment by mahagr** [comment]
As workaround use `--user=username` parameter until the fix has been released.
