### ISSUE TITLE
Can't register a new user - Username already exists

### ISSUE THREAD

**Issue by zacchaeusluke** [getgrav/grav-plugin-login#159]
I'm getting a runtime error when trying to register a new user through the registration form. E.g. "Username "john" already exists, please pick another username", despite this user not existing. Fresh install of Grav & admin plugin.

**Comment by catchlight** [comment]
I'm having the same issue.

**Comment by rhukster** [comment]
I will look at this ASAP.

**Comment by rhukster** [comment]
Fixed, will get this released soon.. In the meantime, it's an easy fix, just remove the code in the linked commit above.

**Comment by catchlight** [comment]
Perfect!

Thanks,
Howard
