### ISSUE TITLE
Create no.yaml

### ISSUE THREAD

**Issue by achwell** [getgrav/grav-plugin-login#160]
New translation to Norwegian
[no.yaml.zip](https://github.com/getgrav/grav-plugin-login/files/2067018/no.yaml.zip)

.

**Comment by Vivalldi** [comment]
Hey @achwell!

Thanks for the effort that you have put into the translation. If you could create a pull request (PR) with the changes that would be much appreciated. You can use the link below to learn how to create a PR. Doing so would also show you as a contributor throughout the projects history.
https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

Best,
@vivalldi
