### ISSUE TITLE
Both ChangePassword and ChangeUserState ignore queried username

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-login#162]
If you attempt to use either the `bin/plugin login passwd` or `bin/plugin login toggle-user` without the `-u` parameter, the command will fail, attempting to work on a user by the name of `1` (true).  

The problem arises when the user is prompted to enter a username, and the validation function is just returning `true`, thus the number `1`.

Submitted a PR with a fix that is similar to the one recently applied to the NewUserCommand.

**Comment by rhukster** [comment]
Merged.  Thanks.
