### ISSUE TITLE
Redirection after Login does not override default behavior

### ISSUE THREAD

**Issue by adamschmid** [getgrav/grav-plugin-login#164]
According to the documentation, manually setting `redirect_after_login: ''` to a page route of choice will override the default behavior of returning a user to the last visited page. This has not been the case. Any time I set this property via `user/config/plugins/login.yaml` OR via `user/plugins/login/login.yaml` it is ignored until I add `login_redirect_here: false` to EVERY SINGLE page markdown file across my entire site (assuming I will not know where a user will try and enter the restricted access area from).

I would like to see the setting `redirect_after_login:` actually override the default behavior and reroute a user to a page of choice. 

Grav v1.4.5
Login v2.7.1

**Comment by rhukster** [comment]
Fixed
