### ISSUE TITLE
'Remember Me' does not work on multiple devices

### ISSUE THREAD

**Issue by TigerHix** [getgrav/grav-plugin-login#168]
If I log in (with 'Remember Me' option checked) on device A, and later log in on device B, and then visit the website with device A again, the following error occurs:

"403 - Someone else has used your login information to access this page! All sessions were logged out. Please log in with your credentials and check your data."

Is it possible to allow users to stay logged in with multiple devices?

**Comment by rhukster** [comment]
This should be fixed in next release..
