### ISSUE TITLE
Error when logging in using OAuth

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-login#17]
![screen shot 2015-11-27 at 21 57 37](https://cloud.githubusercontent.com/assets/11783388/11448094/e99c5632-9551-11e5-9811-16662f18844c.png)

@Sommerregen getting this error while logging in using GitHub (not sure you've already seen this before)

**Comment by Sommerregen** [comment]
Thanks @rhukster for fixing this! :) @flaviocopes It seems like it was a left-over at that time I started writing the classes for the login plugin.
