### ISSUE TITLE
Session expires in 30 mins independent from config settings.

### ISSUE THREAD

**Issue by heavydetail** [getgrav/grav-plugin-login#178]
Hi,
see title, 
**Session expires in 30 mins independent from configuration settings.**

How can I diagnose this problem?
The set cookies have weird expiry dates (like ~18h) which have not been set anywhere and don't seem to be logging the users in.

I am **using the private-site plugin** to secure the whole site.
Session sharing (log in on frontend be logged in in backend too) seems to work OK.
I am guessing the private-site plugin uses this grav-plugin-login for its login procedure,
thats why I am asking here. Even without session sharing and login via backend the same thing happens, logout in 30 mins.

What could be the cause why the session expires in ~30 mins instead of the session expiration of a week (in secs) that i set in the global grav session configuration section?
Do I have to set some session path or any other configuration (in which plugin or in the global yaml file)?
Unsure about the mechanics at play here.

It is frustrating as it happens to all my users constantly and is super annoying for quick edits on a documentation page (theme learn2-git-sync).
Its the newest Grav version (Grav v1.5.1 - Admin v1.8.9) running on Debian 9, nginx.

thanks!

**Comment by heavydetail** [comment]
do you mean the linux setenv command? the PHP putenv() function or the apache_setenv? (i am on nginx)
if its the linux setenv how do i check if its allowed and for whom? www-data?
please explain.

**Comment by mahagr** [comment]
I meant that PHP has a function `setenv()` which can be disabled in PHP configuration by not allowing it to be called.

**Comment by DebuggeR94** [comment]
@mahagr For security reasons, this feature is disabled on many webhosts. 
If Grav depends on this function, this limits the list of available hosting providers...

**Comment by mahagr** [comment]
Should be fixed in latest Grav CI build.

**Comment by mahagr** [comment]
I don't know what it could be, something in your system prevents timeout from being changed.
