### ISSUE TITLE
How to make a page accessible only for unregistered users?

### ISSUE THREAD

**Issue by DebuggeR94** [getgrav/grav-plugin-login#179]
I want to hide login, register, forgot and reset pages from registered users.
I search info about this but do not found nothing.

**Comment by rhukster** [comment]
Is this specific to multilanguage?

**Comment by DebuggeR94** [comment]
Yes, I'm planning a multilingual site, but I do not see the connection with the question.
I created my own login and registration pages, created templates for them.
![image](https://user-images.githubusercontent.com/10379487/45392116-93400f80-b62e-11e8-9f00-b51101c9800a.png)
The problem is that these pages are available for authorized users. Now I solved this problem using a template, checking whether the user is logged on.
![image](https://user-images.githubusercontent.com/10379487/45392333-8e2f9000-b62f-11e8-8bba-659d1a5755fc.png)
But it seems to me that this is a bad decision, and it does not look very good...
I want to try to hide these pages using header: access:

I hope that I clearly explained, and sorry for the typos, English - not my native language.

**Comment by rhukster** [comment]
On this registration page try putting this:

```
login:
    visibility_requires_access: true
```

It won't stop access, but will make it 'invisible' to any navigation, or you could at least check `page.visible`

**Comment by DebuggeR94** [comment]
I successfully hide them from the menu) I would like to protect them from direct access by reference. After all, it's strange when an authorized user can open the registration page.

**Comment by rhukster** [comment]
What would you do? show a 404? redirect to another page? It's kinda hard to know what your workflow would be in this case.. You can just put a message, saying "already registered" if they are logged in and not show the form.

**Comment by DebuggeR94** [comment]
404 it is the best variant)

**Comment by DebuggeR94** [comment]
Yeap, I need ability to redirect authorized user to home page.

**Comment by rhukster** [comment]
I think the best thing to do is to achieve this in Twig with this code:

```
{% if grav.user.exists %}
   {% do grav.redirect('/') %}
{% endif %}
```

This will redirect to the root of the site.. or you could put a `/not-found` url so you get a 404. However for this to work best you should add this to the 'register' page twig.  

I've modified the login plugin (soon to be released) to provide a base `register.html.twig` template (that simply extends `form.html.twig`) that you can override in your theme with this check/redirect logic.

**Comment by RomainLWiz** [comment]
> I think the best thing to do is to achieve this in Twig with this code:
> 
> ```
> {% if grav.user.exists %}
>    {% do grav.redirect('/') %}
> {% endif %}
> ```
> 
> This will redirect to the root of the site.. or you could put a `/not-found` url so you get a 404. However for this to work best you should add this to the 'register' page twig.
> 
> I've modified the login plugin (soon to be released) to provide a base `register.html.twig` template (that simply extends `form.html.twig`) that you can override in your theme with this check/redirect logic.

Is it possible to put a condition that only allows a group to access a page ?
In fact I need that customers is not access to the page but some users.
Thx
