### ISSUE TITLE
Languages not showing

### ISSUE THREAD

**Issue by JDomleo** [getgrav/grav-plugin-login#187]
Our website is in en/de/cs/fr/it/pl/sv and when using the snipped `{{ 'PLUGIN_LOGIN.BTN_LOGIN'|t }}` in our twig files, it only translates for en/de/fr. The other languages display "PLUGIN_LOGIN.BTN_PLUGIN" rather than the translated word of "Login".

**Comment by vanilla-thunder** [comment]
I had same (or maybe similar) issue, but even german was not translated.
Adding --- in the first row of translation file fixed this problem for me.
(see admin plugin translation files for reference)
