### ISSUE TITLE
What about Jasig CAS login support

### ISSUE THREAD

**Issue by sgregori** [getgrav/grav-plugin-login#189]
Hi friends, 

We are using Jasig CAS authentication on wordpress, humhub, nextcloud, rainloop, mautic, glpi, and another apps, and we are thinking to implement on GRAV.

https://github.com/apereo/cas

Implementation on PHP sites is easy and Ruby apps also.

At this time, i didnt found any another plugin like this.

Anyone is working in this feature ?

Thanks a lot, GRAV seems to be a nice alternative to wordpress multi site.

**Comment by rhukster** [comment]
There is no plug-in for for this authentication system currently. Take a look at the oauth2 plug-in or the ldap plug-in to see how easy it is to create custom authentication grav plugins tho.

**Comment by Itacua** [comment]
@sgregori Hello, could you tell me or give me a link of the Jasig CAS plug-in you are using on Humhub? Thanks

**Comment by sgregori** [comment]
Excuse me, i'm revising the code because is mixed with our custom authentication. 

We would try to clean and publish them.
