### ISSUE TITLE
Password reset returns 403 Forbidden

### ISSUE THREAD

**Issue by bobbwal** [getgrav/grav-plugin-login#191]
When I attempt the reset my password the link from the password reset email leads to a 403 error. 
I'm currently trying to work this issue out with my host but we're not having much success.

It's a LiteSpeed server, we've tried excluding mod_security rules but that hasn't solved the issue.

Any suggestions?

**Comment by rhukster** [comment]
what is the URL that is being set in the reset email?

Does this URL lineup with your expected site url?
