### ISSUE TITLE
Login interval shows seconds instead of minutes

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-login#194]
Type: typo

Admin configuration shows 10 `seconds` but if I try it shows 10 `minutes`. It seems that it is really a minutes interval.
I guess the same for reset.

![grafik](https://user-images.githubusercontent.com/7337347/50869526-b0a2a180-13b4-11e9-8789-dc4e6eae1a30.png)

**Comment by rhukster** [comment]
done
