### ISSUE TITLE
"Notification email" not working

### ISSUE THREAD

**Issue by niro93** [getgrav/grav-plugin-login#198]
Hello,

i want to use the option "Send notification email", but it is not working.
The "Welcome Mail" and "Activation Mail" is working fine, but not the Notification for the site admin.
I checked the Debug Mail.log and there is no entry.
The "Email to" Mail is configured.

thank you

**Comment by rhukster** [comment]
What version?

**Comment by niro93** [comment]
Is it working for you?

**Comment by rhukster** [comment]
Yes works fine.  Can you send other email? Have you tried the test email cli command?

**Comment by niro93** [comment]
Other email is working fine, "Registration" and "Forgot Password" for example.

**Comment by niro93** [comment]
The test email via cli command is working, but with some errors.
Is this my problem?
"Message sent successfully!"

`PHP Warning:  PHP Startup: Unable to load dynamic library 'oci8.so' (tried: /usr/lib64/php/modules/oci8.so (libclntsh.so.18.1: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/oci8.so.so (/usr/lib64/php/modules/oci8.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'oci8' (tried: /usr/lib64/php/modules/oci8 (/usr/lib64/php/modules/oci8: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/oci8.so (libclntsh.so.18.1: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_oci' (tried: /usr/lib64/php/modules/pdo_oci (/usr/lib64/php/modules/pdo_oci: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/pdo_oci.so (libclntsh.so.18.1: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by bobbwal** [comment]
Could it be this issue here? [Correct sendNotificationEmail to use plugins.email.to](https://github.com/getgrav/grav-plugin-login/pull/188)

**Comment by rhukster** [comment]
Merged this now.
