### ISSUE TITLE
Server Error for nginx + php-fpm

### ISSUE THREAD

**Issue by linavo** [getgrav/grav-plugin-login#20]
![screen shot 2015-12-04 at 1 57 55 pm](https://cloud.githubusercontent.com/assets/12104092/11600056/f06f4558-9a8f-11e5-9dd9-a54a7b393160.png)

When updating GRAV and the following plugins on an environment (local) that uses apache the error shown above doesn't occur. GRAV version before update is `v1.0.0-rc.4` after update is `v1.0.0-rc.6`

The plugins are...
![screen shot 2015-12-04 at 2 02 41 pm](https://cloud.githubusercontent.com/assets/12104092/11600019/b8a82982-9a8f-11e5-9676-badadc7f0293.png)

When moving from local to production (using nginx + php-fpm) with these updates this error occurs on Chrome, Firefox, and Safari on first page load. After that this error message occurs intermittently.

**Comment by rhukster** [comment]
So are you running on the latest versions of everything? Your screenshot shows numerous updates

**Comment by linavo** [comment]
@rhukster Yes. I included that so you saw what versions I updated from.

**Comment by rhukster** [comment]
Can you first turn on error display in the system yaml.  Then give me a screenshot of the entire error page, that will have a trace that will help me locate where this is coming from (hopefully).

If nothing useful comes of that, can i get a zip of your remote site so i can try to replicate locally. Perhaps a link to a dropbox location?

**Comment by linavo** [comment]
@rhukster unfortunately I can't get you a copy of the site. These are the error messages displayed when changing error display to true.

![screen shot 2015-12-04 at 3 05 59 pm](https://cloud.githubusercontent.com/assets/12104092/11601442/d9d0078e-9a98-11e5-880e-f348d2b5b40c.png)
![screen shot 2015-12-04 at 3 06 10 pm](https://cloud.githubusercontent.com/assets/12104092/11601445/dc60c484-9a98-11e5-96b1-a272eb6f42b6.png)


I hope this helps. Please let me know if you need anything else.

**Comment by w00fz** [comment]
You just go to `/admin` and then you are getting the error?
I tried on a server setup where i have `nginx/1.8.0` running PHP-FPM `PHP 5.6.15` but I am unable to get that same error like you.

```bash
# bin/gpm update
Nothing to update.
```

**Comment by flaviocopes** [comment]
I have a possible idea. Go to user/plugins/login/classes. 
Can you paste the files list?

**Comment by rhukster** [comment]
Another think did you install the remote system via GitHub?  If so have you done a `bin/grav composer` command lately?  This will update the composer libs.

However, this is not necessary if you update Grav normally via GPM.

**Comment by w00fz** [comment]
Ok seems like I can reproduce the issue and @flaviocopes is onto something.
Look into your `user/plugins/login/classes` and you should have `controller.php`, you want to rename that to be `Controller.php`.

**Comment by Sommerregen** [comment]
@linavo It seems like an update problem... either you rename that file (as @w00fz ) or delete the login folder and install it again.

**Comment by flaviocopes** [comment]
Added this to the known issues https://github.com/getgrav/grav-plugin-login/blob/develop/README.md#known-issues to point others that might have the same problem

**Comment by linavo** [comment]
I tried your work around for the issue but changing the case doesn't resolve the issue still. The page loads fine after a refresh but regardless of what browser you're on that error message always appears after a `clearcache` on the most recent version of this plugin.

**Comment by rhukster** [comment]
This has been resolved for quite some time.  I think you must be missing some updates?

**Comment by linavo** [comment]
I just updated everything today and saw this error again.

**Comment by flaviocopes** [comment]
Can you send me your `user/` folder via Gitter PM? I'll test it. You can remove the accounts subfolder.

**Comment by linavo** [comment]
@flaviocopes it's sent.

**Comment by w00fz** [comment]
Hi @linavo I had a look at this, using your `user` folder and testing on my nginx server and I cannot reproduce anymore.
Could you double check you are all up to date with Grav and Plugins? Also, you might want to try disabling any cache, Grav cache, apcu/opcache.

The issue that I was once able to reproduce has been solved with the renaming of the controller file and for me it is all working as expected now.
