### ISSUE TITLE
grav.user.username is not reliable

### ISSUE THREAD

**Issue by otahirs** [getgrav/grav-plugin-login#201]
Hi,
I found out that user can stop being authenticated, but the username still persist present set in the session which leads to some troubles when using _if(grav.user.username)_  condition to display content only for the logged in users as some parts are showed because the condition is met, however, the rest that requires further authorization is not being displayed.

I am currently trying to replicate this issue, but in the debbug console it looked like this:

> "username" => "ota"
> "authenticated" => false
> "authorized" => false

I moved to using _if(grav.user.authenticated)_ that seems to be reliable all the time. Are there any downsides to this usage or should it be changed in the documentation as the default approach?? Am I missing something here?

I will update the issue if I will find how to replicate it. Currently I think it is happening after being idle for an extended period of time.

**Comment by mahagr** [comment]
Yup, do not rely on username. It can be set in multiple instances even if the user isn't fully logged in. Instead of that you should do `user.authorize('site.login')` or `user.authorize('admin.login')`.

**Comment by otahirs** [comment]
**Thanks**, I was following the example code in readme

```
{% if config.plugins.login.enabled and grav.user.username %}
     <li><i class="fa fa-lock"></i> {% include 'partials/login-status.html.twig' %}</li>
 {% endif %}
```

**Comment by Vivalldi** [comment]
@otahirs just to help clarify the example is for a UI "nicety." Basically, if we have a username let's say "hello" so to speak. Using @mahagr's snippet above will most definitely get you what you're looking for.
