### ISSUE TITLE
I do not understand how to add links 'regsiter' or 'forgot password' to login screen

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-login#212]
I do not understand how to add link to regiter or forgot password to login screen?
need help

**Comment by lufog** [comment]
Not sure if this is the right place for such questions...
In any case, I do not understand what you have difficulties, with editing the template file?

**Comment by lufog** [comment]
I hope you have an understanding of the templates work in grav.
And what if the required ```.twig``` file is not found in the theme ```templates``` folder, it is taken from the ```templates``` folder of the plugin.
