### ISSUE TITLE
Default login route not set

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-login#213]
The login.yaml file reads:

```
route:               # Specific route for Login page (default is '/login')
```

But that comment is not true - unless you manually configure `route:login`, navigating to /login throws a 404 error on the latest Grav + Admin with Quark theme.

**Comment by rhukster** [comment]
Correct, the default is to show the login form 'on' the page you are trying to access. However, if you want to have a specific landing page, then you should provide a route, and then, `/login` is the default expected.
