### ISSUE TITLE
How to translate page strings?

### ISSUE THREAD

**Issue by francoisjacquet** [getgrav/grav-plugin-login#214]
Hello,

Thank you for this great plugin.

Having a multi-language site, I have followed instructions to translate pages and this is working well.
However, plugins do no seem to obey to this rule:

Creating a `user/plugins/pages/login.fr.md` or a `user/plugins/pages/login/default.fr.md` does not work.

So, how can we translate, for example, the ["User Login"](https://github.com/getgrav/grav-plugin-login/blob/develop/pages/login.md#user-login) string?

**Comment by francoisjacquet** [comment]
Is there any way to translate plugins?

**Comment by lufog** [comment]
Everything works on my site. Or did I misunderstand your problem?

Redefined Page:
![image](https://user-images.githubusercontent.com/10379487/63227724-4bd4e280-c1f2-11e9-8e06-bed52398d02a.png)

English:
![image](https://user-images.githubusercontent.com/10379487/63227665-9ace4800-c1f1-11e9-9d4c-dce52a14b857.png)
Russian:
![image](https://user-images.githubusercontent.com/10379487/63227667-a457b000-c1f1-11e9-9e9f-1b89f43981a4.png)
Ukranian:
![image](https://user-images.githubusercontent.com/10379487/63227673-b2a5cc00-c1f1-11e9-9116-6102a4377908.png)

**Comment by francoisjacquet** [comment]
Thanks @lufog 

Placing the translated files into the `user/pages/login/` did work after setting the custom **login route** to `login/` in the plugin configuration.
