### ISSUE TITLE
[Question] What is the best approach for user-specific pages?

### ISSUE THREAD

**Issue by Yandols** [getgrav/grav-plugin-login#221]
I probably worded the title wrongly and this might not be the most appropriate place to ask this question but since it involves the login plugin I'm going to ask here.

I'm trying to set up a system where users can login to retrieve a unique serial number for another service I have available as well as a few files that are unique to the specific user that logged in.

My question is, how do I go about securing the pages and files that shouldn't be accessible by other users? I read through the documentations and found only ways of protecting pages (and their subpages) through groups. So if I make a main page containing subpages with each and everyone's unique serial number and files in their own subpage, everyone that has login access can just directly access someone else's page by changing the url in their browser (for example by changing the url from `example.com/panel/usercontent/jeffery` to `example.com/panel/usercontent/kenneth`).

If there is something in the documentation that I missed or was not aware about where I can achieve this, please let me know and point me in the right direction.

Or alternatively, is the a way or another plugin I can use to make it so that going to the same page (for example `/panel/usercontent`) yields a different file for the user that is logged in?

I've always used grav for something more simple and this is the first time I'm doing a site that's much more complicated than I originally thought.

Do let me know how or whether not I can go about this, thanks.
Yandols.

**Comment by mahagr** [comment]
Grav uses permissions and groups, you can use both or either one which you want. If you use permissions, you just need to set access in the header and then during login (fill the permissions based on the external service. Or just hook into onPageInitialize event and prevent access if the custom requirements aren't met. So you can also customize Grav for your own permission system.
