### ISSUE TITLE
Redirect after login not redirecting to the path set

### ISSUE THREAD

**Issue by otahirs** [getgrav/grav-plugin-login#223]
When "Redirect after login" path is set, I am not redirected to the "redirect after login" page, but instead I am reloaded to the login page again.

 v3.0.3
(When the path is not set, the user is successfully redirected back to the previously visited page.)

**Comment by mahagr** [comment]
I just tested this feature and it seems to work just fine for me.

**Comment by otahirs** [comment]
I deleted the plugin folder and cloned again. The problem is resolved. Sorry for any inconvenience.
