### ISSUE TITLE
"Redirect after activation" missing from config file

### ISSUE THREAD

**Issue by Bennycopter** [getgrav/grav-plugin-login#224]
The `login.yaml` file is missing the config option `user_registration.redirect_after_activation`.

The option is referenced in login.php on line 374, and it seems to be fully functional... it's just missing from the config file.

**Comment by rhukster** [comment]
You can submit a PR by going here: https://github.com/getgrav/grav-plugin-login/blob/develop/login.yaml

clicking edit, make your addition and saving.  it will create a PR automatically.

**Comment by Bennycopter** [comment]
Thank you!  I'm new to GitHub, so I didn't know about that.  I made the pull request.

**Comment by rhukster** [comment]
I think you missed the last step where it says "create pull request" in a green button? You probably have a local clone of `grav-plugin-login` repo, and if you go there, it should prompt you.

**Comment by rhukster** [comment]
https://github.com/Bennycopter/grav-plugin-login

Make the changes to the file directly here, then you should see the green button to create the pull request.  Thanks!

**Comment by Bennycopter** [comment]
I think I got it this time :)

**Comment by mahagr** [comment]
Looks like this has already been fixed.
