### ISSUE TITLE
[Question] How to grant access to a page/subfolder on a restricted folder ?

### ISSUE THREAD

**Issue by breucker** [getgrav/grav-plugin-login#227]
Hi
I hope I'm in the right place to ask, forgive me if I'm not...

I try to have a global protected grav instance, at the top level. For that I used the parent_acl set to 'true' on each top level page of my pages directory as suggested in #136. 
With this configuration, I was wondering if it's possible to allow access to everyone (guest included) for one page or subfolder ?
 In other words, is there an access permission that would _allow_ access instead of _restricting_ it ? Since the parent_acl configuration searches for parent access rules when there is none, and to my knowledge the only way of allowing access to a page is to not set the "access" frontmatter option, I'm kind of stuck here...

Thanks !
Philippe

**Comment by mooomooo** [comment]
Any updates to this?  I too have the same question.  Setting the access frontmatter option to "false" prevents logged in users from accessing the page until they log out.

**Comment by ricardo118** [comment]
i dont think there is an option built in, you could go around this with some custom php in a plugin/theme.

in the meantime ill take a look to see if there's some workaround

**Comment by mooomooo** [comment]
In terms of the workaround -- is there ever a reason to prevent access to logged in users?  After all, they are always able to log out and thereby get access.  My intuition would suggest that an access value of "false" should allow either logged in or not logged in users to access: it just shouldn't check the login status, not check that the login status equals the access value.

That being said, if there is value in preserving that functionality, then perhaps the access value can take on a tristate value true / false / null, with null representing the case where the login status is not checked, and the two booleans requiring equality.

**Comment by ricardo118** [comment]
page access have been greatly modified/improved over grav 1.7, its possible this is already possible but yet undocumented

**Comment by rhukster** [comment]
```
---
title: 'Guest Only'
access:
    site.login: false
---

Only if you are guest user
```
