### ISSUE TITLE
Reset/Change password from CLI

### ISSUE THREAD

**Issue by gagarine** [getgrav/grav-plugin-login#23]
Now the CLI of this plugin let you create a new user with "bin/plugin login new-user". You can modify account by simply editing the user's files in user/accounts. But it's harder to quickly edit the password.

It would be nice to  have a command to change the password something like:
$ bin/plugin login passwd username
$ new password :

**Comment by w00fz** [comment]
Yes, valid points. Now plugins can run their own CLI, we can definitely add more functionalities.
As well as `passwd` I was thinking also a `deluser` and `edituser` and perhaps a few shortcuts like `disable` and `enabled`, to quickly disable users.

**Comment by Vivalldi** [comment]
@w00fz I think we can close this issue

**Comment by w00fz** [comment]
:+1:
