### ISSUE TITLE
Minified CSS

### ISSUE THREAD

**Issue by lukecurtis93** [getgrav/grav-plugin-login#237]
When using this plugin our Semrush site audit flags the css files are not minified. 

Is there some commands or way to minify this? Found at `/css/login.css`

**Comment by rhukster** [comment]
Grav does this automatically if you turn on the css pipeline.

**Comment by lukecurtis93** [comment]
Perfect toggling
```
assets:
  css_pipeline: false  
```

to `true` fixed the issue. Appreciate your quick reply!
