### ISSUE TITLE
Login -> DEBUG is enable on the latest release

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav-plugin-login#244]
Hello,

On the latest release, the [constant DEBUG of the Login class is set to 1](https://github.com/getgrav/grav-plugin-login/blob/develop/classes/Login.php#L36).
I'm not sure that match [the changelog](https://github.com/getgrav/grav-plugin-login/commit/b47f6ef0560d24596a8f5818e7e592aad1d3dd43#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR8)
```
Added some debugging messages (turned off by default)
```

Regards,
Anael

**Comment by mahagr** [comment]
Good catch. No need to have those turned on. :)
