### ISSUE TITLE
Option to show "Login" link

### ISSUE THREAD

**Issue by HunterDG** [getgrav/grav-plugin-login#251]
I hope I'm not missing something obvious, but a setting in the Login plugin to _show_ "Login" link in the menu  (where "Logout" is when logged-in) would be very nice!

**Comment by rhukster** [comment]
Just copy the `partials/login-status.html.twig` file into your theme's `templates/` folder (keep the partials dir) and edit it as you need:

https://github.com/getgrav/grav-plugin-login/blob/develop/templates/partials/login-status.html.twig

Or just take this example and directly copy/paste it into your theme's menu/header.

**Comment by HunterDG** [comment]
I've done this, but thought a simple toggle would be nice.  :)
