### ISSUE TITLE
User Accounts cache

### ISSUE THREAD

**Issue by garytube** [getgrav/grav-plugin-login#252]
Grav v1.6.11 - Admin v1.9.7 

The Admin User account does not reflect the the permissions set in [USER].yaml file.
Seams to be cache related. Is this indented? It would be greate if I can update User Accounts without manually clearing the cache. 

![image](https://user-images.githubusercontent.com/3823504/62930155-242de680-bdbc-11e9-9ebb-e7c67ed98ccb.png)

**Comment by mahagr** [comment]
Should now be fixed for the next login version, though you need to enable the `Sync User in Session` setting in order to make it to work. It also only works in Grav 1.7 because of some limitations in the older implementation.

**Comment by funktionaer** [comment]
Dear all,

I’m experiencing an issue with the Login Plugin (Grav v1.7.48, Admin v1.10.48, Login v3.7.9).

I have enabled the` Sync User in Session` option, expecting user data in the session to be updated when changes are made via the Admin Panel. However, this does not seem to work as expected:

**Scenario:** When I update user data using the /user_profile route on the frontend, the session reflects these changes correctly.
**Issue:** When I update the same user via the Admin Panel, the session does not reflect the changes at all.
Is this the intended behavior, or is there a configuration step I might have missed?

Looking forward to your guidance!

Best regards,
-funktioner
