### ISSUE TITLE
visibility_requires_access corrupting frontmatter

### ISSUE THREAD

**Issue by no10staples** [getgrav/grav-plugin-login#255]
If I am using
```
login:
    visibility_requires_access: true
```
in the frontmatter of a page, when I edit the page using the Admin interface, the login config gets inserted into the frontmatter. The workaround is to edit the page manually, but this appears to be a bug.
![56330197-05447e00-6155-11e9-8562-44090c0626b4](https://user-images.githubusercontent.com/36873341/83830435-79126300-a728-11ea-9c3d-59518daf973f.png)

**Comment by rhukster** [comment]
What plugins do you have installed?

**Comment by no10staples** [comment]
Hi Andy

[cid:image001.png@01D63B7B.111CBAC0]

Login-Ext is mine. It adds a couple of static functions and more access roles. Let me know if you need anything else.

Dan

**Comment by rhukster** [comment]
Image broken ? Looks like you replied via email. Try via site.

**Comment by no10staples** [comment]
![1](https://user-images.githubusercontent.com/36873341/83869077-52c3e600-a76f-11ea-86c3-69074019f4c9.png)

**Comment by rhukster** [comment]
Duplicate of https://github.com/getgrav/grav-plugin-login/issues/228

fixed.
