### ISSUE TITLE
Is it possible to see who is currently logged in?

### ISSUE THREAD

**Issue by gambithunt** [getgrav/grav-plugin-login#261]
Hi here

Is it possible to see who is currently logged in?

Thanks.

**Comment by Vivalldi** [comment]
Yup! Take a look at the [login-status template](https://github.com/getgrav/grav-plugin-login/blob/develop/templates/partials/login-status.html.twig) for an example

**Comment by jubmailto** [comment]
Is it possible to explain more about this ?
What do I have to do with login-status.html.twig ?
Thanks
