### ISSUE TITLE
Admin creates incorrect frontmatter for visibility_requires_access

### ISSUE THREAD

**Issue by paulrudy** [getgrav/grav-plugin-login#265]
When using the admin panel to set Security > Page Access > "Menu Visibility Requires Access", the frontmatter produced is

```yaml
visibility_requires_access: true
```

when it should be:

```yaml
login:
    visibility_requires_access: true
```

**Comment by rhukster** [comment]
thanks: https://github.com/getgrav/grav/commit/44ad0ca1eab4a6407749f15ce33bc05fa18258de
