### ISSUE TITLE
Connection problem with 2FA 

### ISSUE THREAD

**Issue by PerChave** [getgrav/grav-plugin-login#276]
Following the update (3.4.2), the connection with 2FA does not work anymore. When the 2FA code is given, it connects and disconnects at the same time. There is also the POST request /admin/task:getNotifications which returns a 401.

Admin panel has also been updated at the same time.

<img width="1680" alt="Capture d’écran 2021-04-08 à 17 57 20" src="https://user-images.githubusercontent.com/9519353/114059274-804c5500-9894-11eb-8a9d-b15ca53c37a2.png">

![Capture d’écran 2021-04-08 à 18 02 43](https://user-images.githubusercontent.com/9519353/114059449-a96ce580-9894-11eb-8364-8e9cf705ebb1.png)

**Comment by mahagr** [comment]
This is an admin issue, see https://github.com/getgrav/grav-plugin-admin/issues/2109#ref-commit-9108a4a

**Comment by PerChave** [comment]
Thanks
