### ISSUE TITLE
XSS in /forgot_password

### ISSUE THREAD

**Issue by Misha-N** [getgrav/grav-plugin-login#298]
Hello, 
i found that there is reflected XSS vulnerability in /forgot_password end.
If I send request with <script></script> in it, withou client side validation, script is returned in response and is perfomed on client side.
I did not find any solution how to fix it, can you help me with that ? :)

Thank you, Mike

**Comment by rhukster** [comment]
Please follow this process to report security issues.

https://learn.getgrav.org/17/security/reports

Thanks!
