### ISSUE TITLE
Typo in class name: Utilis should be Utils

### ISSUE THREAD

**Issue by noopable** [getgrav/grav-plugin-login#303]
https://github.com/getgrav/grav-plugin-login/blob/1d60bee210142d215b145a931874364458749ed1/classes/Email.php#L46

The class name Utilis is incorrect and likely meant to be Utils. Correcting this will prevent potential errors in code execution.
I apologize for not being able to attach a pull request for the correction.

**Comment by rhukster** [comment]
Eek. Good catch. Will fix asap.

**Comment by noopable** [comment]
Thanks
