### ISSUE TITLE
Mkdir() not allowed for plugin://login/pages/.revs

### ISSUE THREAD

**Issue by ramsnerm** [getgrav/grav-plugin-login#306]
**Issue Description:**

While working with the **Login plugin**, I encountered an issue where enabling 2FA causes the following error to occur during the login process:

`mkdir() not allowed for plugin://login/pages/.revs/...`

If 2FA is disabled, everything functions as expected. However, when 2FA is active, the error prevents me from completing the login.

---

**Steps Taken to Resolve the Issue:**

We have already tried the following approaches, but none of them resolved the problem:

- Ensured correct directory permissions, including temporarily setting them to `777`.
- Manually configured streams in `system.yaml` to ensure proper path resolution.
- Redirected 2FA data to a writable path like `user/data/twofa`.
- Disabled Admin revisions during the login process and re-enabled them after successful login.
- Cleared the cache multiple times after every change.
- Tested with different combinations of 2FA and Admin revisions.

Despite these efforts, the issue persists, and 2FA cannot function alongside Admin revisions during the login process.

---

**Observation:**

Interestingly, if Admin revisions plugin is activated **after login** (https://github.com/david-szabo97/grav-plugin-admin-addon-revisions, Vesion: Release v2.0.1), both features work without any issues. The error seems to occur specifically during the login phase when both 2FA and Admin revisions are active.

---

**Expected Behavior:**

2FA and Admin revisions should function simultaneously during the login process without triggering errors.

---

**Environment Details:**
- Grav version: 1.7.48
- Login plugin version: 3.7.9
- PHP version: 8.2

Please let me know if further details are needed!

**Comment by rhukster** [comment]
This is definitely an issue with the revs addon plugin.  It's not an issue with login or 2fa.  The error clearly is trying to writes a revs file inside the plugin pages folder which does not exist.  You should open a ticket on the revs addon plugin repo.  Or disable it.
