### ISSUE TITLE
Bug input and label Username and Password

### ISSUE THREAD

**Issue by fbardel** [getgrav/grav-plugin-login#36]
Hi,

Two bugs for Username and Password fields 
 * translation does not work
 * attributs "for" and "id" are missing respectively for label and input

Those example are from the plugin maintenance...

![bug_accessibility](https://cloud.githubusercontent.com/assets/5451956/12212284/f94b7a58-b668-11e5-9e17-b3a318877f22.png)
![bug_fr](https://cloud.githubusercontent.com/assets/5451956/12212283/f94807ce-b668-11e5-8cfa-878f38e85c34.png)

Thanks ^^

**Comment by Vivalldi** [comment]
i'll take a quick look tomorrow about those translations.  is this on a default login page? because that green looks weird

**Comment by fbardel** [comment]
Whhhhaaaat ??? my green is weird !! ^^
It's a very ancient green ! a very very old green ! XD

**Comment by Vivalldi** [comment]
@fbardel The labels have been updated to be translatable... (currently in the develop branch)

I'm not seeing a reason to need the for attribute or an id either. May I suggest closing the issue as those attributes are not needed?

**Comment by fbardel** [comment]
@Vivalldi : the for attribute it's an accessility thing : [https://www.w3.org/WAI/tutorials/forms/labels/](https://www.w3.org/WAI/tutorials/forms/labels/)

**Comment by Vivalldi** [comment]
Alright! I'll look at that as well though I believe it may be controlled in the forms plugin.

**Comment by flaviocopes** [comment]
All merged!

**Comment by Vivalldi** [comment]
I believe this can be closed
