### ISSUE TITLE
protected site still displays content

### ISSUE THREAD

**Issue by josefstr** [getgrav/grav-plugin-login#42]
I want to set a page protected, this works in the way that a "login display" is provided for the site, but there is also the content of the site shown.

theme: antimatter

the file is:

> bash-4.1$ cat pages/06.private/default.md

> ---
> title: Private
> access:
>    site.private: true
>    admin.login: true
> ---
> 
> protected stuff
> 
> 
> 
> protected stuff
> 
> protected stuff
> 
> 
> 
> protected stuff

![2016-01-27-201629_1918x1179_scrot](https://cloud.githubusercontent.com/assets/348359/12626251/13b35432-c538-11e5-829f-1d6a3e81aab9.png

**Comment by Vivalldi** [comment]
If you're using the login plugin to secure the page the correct method is as follows
```
 access:
    site.login: true
```
If this does not fix it can you copy and paste the header of your page? (everything in between the two `---`)

this gives access to users who have login rights. 
using `admin.login` should not affect it

**Comment by Vivalldi** [comment]
From what I am currently seeing it looks like you're trying to use the private plugin and not the login plugin.

**Comment by rhukster** [comment]
Oh my bad, i told him to post here without really digging in and realizing it was not the login plugin.

Suggestion however, use this Login plugin rather than the Private plugin which is from a 3rd party and we don't support

**Comment by Vivalldi** [comment]
:+1:

**Comment by josefstr** [comment]
I didn't use any 3rd party plugin. I tried to setup: http://learn.getgrav.org/advanced/groups-and-permissions
The screenshot provided was my mistake as I had still the access.site.login{true} value set for the user. Removing it just shows the content the user has access to. Setting the access direct to the user is working but inheriting it from a group doesn't work.

> $ cat user/config/groups.yaml
> private:
>   icon: users
>   readableName: 'Private only'
>   description: 'just for private use'
>   access:
>     site:
>      private: true

user with no access:
> groups: private
> state: enabled

user with access:

> access:
>   site:
>     private: true
> groups: private
> state: enabled

**Comment by flaviocopes** [comment]
Set 

```yaml
groups:
  - private
```

instead of

```yaml
groups: private
```

A fix is coming with the next Grav release.

P.s. I assume the groups.yaml is correctly indented, here from your paste I do not see it. Put code snippets in triple backticks next time.

**Comment by josefstr** [comment]
$ cat user/config/groups.yaml
```private:
  icon: users
  readableName: 'Private only'
  description: 'just for private use'
  access:
    site:
      private: true
```

but changing the design in user doesn't solve the problem:
```
groups:
  - private
```

I'm using grav 1.0.4 as I'm still on php 5.4

**Comment by flaviocopes** [comment]
Works for me. No page content is shown, just the login form. Please post as much details as you can to recreate the problem. Paste the page content properly formatted. The content appearing below the login form is content from that page?

**Comment by josefstr** [comment]
Same here, no page content is show, login form is shown. But after I log in I still cannot see the page content, still access denied when I want to access with group privileges. Accessing directly with user:
```
access:
  site:
    private: true
```
is working. So this issue can be closed, it's probably about group policy or I've messed something up.

**Comment by flaviocopes** [comment]
After the login, are you redirected to the protected page, or is it still showing the login form URL?

E.g. `http://localhost:8080/grav/login` or  `http://localhost:8080/grav/your-page-url`?

**Comment by josefstr** [comment]
I'm redirecting to root "/" after login, but trying the protected site, besides I'm logged in, with group inheritance doesn't work.

**Comment by josefstr** [comment]
group problem was duplicate of:
https://github.com/getgrav/grav-plugin-login/issues/40

**Comment by flaviocopes** [comment]
Need to remind myself to test issues with the latest stable release! Was already fixed in the develop branch, hence it worked for me but not for you :+1:
