### ISSUE TITLE
protect dropdown menu links on procted site

### ISSUE THREAD

**Issue by josefstr** [getgrav/grav-plugin-login#46]
If you're setting up a protected site with subpages and enabling the dropdown menu for those subpages the drop down menu(links to subpages) is also shown when you're not logged in. It would be better if the dropdown menu is also hidden when the parent page is protected.

**Comment by flaviocopes** [comment]
This is not a responsibility of the Login plugin. The login plugin knows nothing about menus.

It's the theme that must implement menus taking into account that a dropdown menu has to be hidden when a parent is protected, so you can raise the issue on the theme you're using.
