### ISSUE TITLE
Oauth links not showing

### ISSUE THREAD

**Issue by Ricoom** [getgrav/grav-plugin-login#47]
Oauth is setup and Yaml settings are correct and everything is enabled but provider links are not showing up. @Sommerregen

**Comment by Vivalldi** [comment]
What version of the plugin are you using? It seems someone else is having issues with this OAuth. I'll pull down and test the latest release as well as the develop branch from github later this afternoon.

Also, can you test the functionality by visiting example.com/login/oauth:facebook (or whatever provider)

**Comment by Ricoom** [comment]
Using 1.3.0 and using direct link doesnt seem to have effect
http://www.kmstest.tk/login/auth:Google

**Comment by flaviocopes** [comment]
@Ricoom might have found an issue when accessing the login page directly without it being called by a page with ACL rules. 

Please try the latest `develop` branch version, let me know if this solves the issue you're having.

**Comment by Ricoom** [comment]
No I did enter page with ACL rules. Now it displays links correctly, but all they seem to do is redirect back to /login without actually opening oauth window to verify or login to particular provider tested with facebook and google I believe that even if something would be setup incorrectly on my side it should open a box with oauth error message or am I wrong?

**Comment by flaviocopes** [comment]
Just tested with a Github OAuth flow. It works correctly for me out of the box. I just created an app and put the credentials in the Grav Login Plugin settings.
It goes to the provider only if it's the first time.

**Comment by Ricoom** [comment]
Hmm not sure what might be the issue then on my side

**Comment by flaviocopes** [comment]
PM me your user/ folder zipped in Gitter, I'll take a look

**Comment by flaviocopes** [comment]
Happens when the `redirect` Login setting is set. Should not be involved during OAuth processing.

**Comment by flaviocopes** [comment]
Fixed in the next release
