### ISSUE TITLE
Issue with authenticate method in LoginController.php. It's possible for a user to be authorised but not authenticated after login.

### ISSUE THREAD

**Issue by antony-o** [getgrav/grav-plugin-login#48]
**Steps to reproduce:**

1. Type in an incorrect password for a valid username.
2. Instead of the "login failed" message, the user is redirected back to the login page and the message "you have successfully been logged in" is displayed.
3. Type in an incorrect username and any password.
4. The login page displays the "login failed" message as expected for step 2.

**Solution:** 

In LoginController.php, I changed the lines 214-218 to:

                    // Authenticate user.
                    $user->authenticated = $user->authenticate($form['password']);

                    if ($user->authenticated) {
                        $this->grav['session']->user = $user;

and lines 237-238 to:

        // Authorize against user ACL
        $userAuthorized = $user->authorize('site.login');
        $user->authenticated = ($user->authenticated && $userAuthorized);

        return $user->authenticated;

to get the login form to work as expected.

**Comment by flaviocopes** [comment]
Reproduced, the user is not actually authorized but it shows the wrong message. Fixed in https://github.com/getgrav/grav-plugin-login/commit/7c12883d165511da8fdc4e3fb1c131233a1cf523

**Comment by antony-o** [comment]
Ok, thanks for sorting.
