### ISSUE TITLE
Forgot Password page issue: Validation message is not displayed if a blank or invalid username is used

### ISSUE THREAD

**Issue by antony-o** [getgrav/grav-plugin-login#50]
**Steps to Reproduce:**

1. On the Forgot Password page, enter a username that does not exist, or leave the username blank.
2. Press "Send Reset Instructions".
3. A 404 message is displayed instead of the validation error message.

**Solution:**

The redirect links for error messages in the taskForgot method of LoginController.php have been hardcoded to the route "/forgot". 

In the taskForgot method replace all the lines:
`$this->setRedirect('/forgot');`
with:
`$this->setRedirect($this->grav['config']->get('plugins.login.route_forgot'));`

**Comment by flaviocopes** [comment]
Good find. 

Forgot was originally only used in the Admin Login Form. 

Need to 
- [ ] detect if it's in the admin and still use `/forgot`, while in the frontend use `route_forgot` as you said. 
- [ ] tweak the strings (use PLUGIN_LOGIN strings in the front)
- [ ] do not allow the form to be sent if there's no username entered.

**Comment by antony-o** [comment]
Hi, 

Yes, I was glad you added the forgot password facility but I ran into some issues when testing it out. I'm logging any issues I find so that I can remove my temporary hacks :)

**Comment by flaviocopes** [comment]
Fixed in the next update
