### ISSUE TITLE
Reset Password Page Issue:  Validation message is not displayed if the new password fails validation.

### ISSUE THREAD

**Issue by antony-o** [getgrav/grav-plugin-login#51]
**Steps To Reproduce:**
1. Generate a reset password email using the "Forgot Password" page for a user account where you have access to the email.
2. Click the reset link in the email.
3. Enter a blank password or one that does not meet the complexity requirements, e.g. "123".
4. A 404 message is displayed instead of the validation message.

**Solution:**
The redirect link is not set before the validation is checked, the reset password page needs user and token params in the url to be displayed.
Add the following lines to the taskReset method before `$user->validate();` is called
in LoginController.php:

                    $param_sep = $this->grav['config']->get('system.param_sep', ':');
                    $resetLink = $this->grav['base_url_absolute'] . $this->grav['config']->get('plugins.login.route_reset') . '/task:login.reset/token' . $param_sep . $token . '/user' . $param_sep . $username . '/nonce' . $param_sep . Utils::getNonce('reset-form');
                    $this->setRedirect($resetLink);
                    $user->validate();

**Comment by flaviocopes** [comment]
Fixed in the next release
