### ISSUE TITLE
Cosmetic:  Some plugin error messages are displayed with the default "info" style rather than the "error" style

### ISSUE THREAD

**Issue by antony-o** [getgrav/grav-plugin-login#52]
E.g. In the "execute" method in Controller.php. I've changed:
            `$this->setMessage($e->getMessage());`
to
            `$this->setMessage($e->getMessage(), 'error');`

Also where the following error messages are used in the plugin, I've made the same change:

- PLUGIN_LOGIN.ACCESS_DENIED
- PLUGIN_LOGIN.LOGIN_FAILED
- PLUGIN_LOGIN.OAUTH_PROVIDER_NOT_SUPPORTED

**Comment by flaviocopes** [comment]
Good catch! You can propose the change directly by posting a PR https://help.github.com/articles/using-pull-requests/ if you like, so your contribution is stored in the repo :+1:

**Comment by antony-o** [comment]
Ok will do. I'm conscious that my quick fixes may not be quite what you need as you have to consider the Admin plugin, etc., so please feel free to disregard my changes and reimplement.

**Comment by flaviocopes** [comment]
Closing, fixed by https://github.com/getgrav/grav-plugin-login/pull/53
