### ISSUE TITLE
Oauth user creation implementation bug

### ISSUE THREAD

**Issue by Ricoom** [getgrav/grav-plugin-login#55]
So if johnsmith@gmail.com where name is set to 'John Smith' logs in has user created john_smith.google then johnsmith2313@gmail.com who aswell has name 'John Smith' tries log in he doesn't get a user created because john_smith.google allready exists.

**Comment by flaviocopes** [comment]
Fixed for the next release by https://github.com/getgrav/grav-plugin-login-oauth/commit/ca4d915b462c213906545f30fa88f3681bf253cd#diff-ff35b2ab04cabcbaa81c3f03339369d4R279
