### ISSUE TITLE
Issues with Access denied and content

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-login#59]
So I have found a couple of issues with the login plugin used on the front end. I don't know whether this is something to do with my setup or actually the plugin.

These happen if I try to access a page that my chosen user does not have permission for. After the login form has been completed the user does see the "Access Denied" message for the page, however I am also seeing the actual content of that page to which I am supposed to be denied. 

By removing the `{{ content }}` token form the login-form.html.twig This can be resolved  but then content of the login plugin such as its headers has to be manually inserted into the template.

Also once at the access denied screen I am still seeing the login submit button (no other form components), and there is no way to go back to a new login screen whit out doing a hard reload. Ideally I would like there to be a log out and try again button.

**Comment by flaviocopes** [comment]
Using version `1.3.1`?

**Comment by flaviocopes** [comment]
Good catch. Will be solved in the next release
