### ISSUE TITLE
Redirect on login not working.

### ISSUE THREAD

**Issue by btn0s** [getgrav/grav-plugin-login#60]
```
redirect: /main
```
is set in the login.yaml file, and reflects under the 'redirect on login' section of the admin dashboard as well. Here's the login function of my `LoginController.php`:  

```
public function taskLogin()
    {
        $t = $this->grav['language'];
        if ($this->authenticate($this->post)) {
            $this->setMessage($t->translate('PLUGIN_LOGIN.LOGIN_SUCCESSFUL'));
            $referrer = $this->grav['uri']->referrer('/');
            $this->setRedirect($referrer);
        } else {
            $user = $this->grav['user'];
            if ($user->username) {
                $this->setMessage($t->translate('PLUGIN_LOGIN.ACCESS_DENIED'), 'error');
            } else {
                $this->setMessage($t->translate('PLUGIN_LOGIN.LOGIN_FAILED'), 'error');
            }
        }

        return true;
    }
```
and everything looks kosher to me, but I'm not even sure I'm looking in the right place... and I'm level 0 in the PHP skilltree.

Do I need to be looking in the `Controller.php` at the redirect functions there instead? Thanks in advance.

**Comment by Vivalldi** [comment]
This has actually been fixed in https://github.com/getgrav/grav-plugin-login/commit/30fa16c33ac060e31c2dffc567d58c9159871792

**Comment by btn0s** [comment]
ah! thank you again.
