### ISSUE TITLE
Editing the registration and login pages. 

### ISSUE THREAD

**Issue by btn0s** [getgrav/grav-plugin-login#61]
Correct me if I'm wrong but as of now the registration page has to be edited _outside_ of the plugin (in my theme's form template), and the login page has to be edited _inside_ the plugin (the plugin's form template). This makes things pretty confusing when you want them both to look the same, and want to be able to use one template for both of them. 

Is there a better way for me to go about this? Maybe it's too late to get this in the next release but could we maybe have the registration be included in the plugin as it's own page+template?

**Comment by btn0s** [comment]
Nevermind, it is editable in the same way. Maybe just include that in the docs. :)

**Comment by flaviocopes** [comment]
If you discover something that should be better documented, please propose a PR for the README.md file as you have a fresh memory of what you'd need to know, and how should it better explained.

**Comment by btn0s** [comment]
I'll make a note and get on that for sure man. Thank you!

**Comment by flaviocopes** [comment]
There's a bit of confusion now as the current README is for the unpublished version. Refer to https://github.com/getgrav/grav-plugin-login/tree/master to see the one of the latest release.
