### ISSUE TITLE
Username/Password field switch with Tab not working

### ISSUE THREAD

**Issue by kLOsk** [getgrav/grav-plugin-login#7]
Hi,
I noticed that the tab key doesn't switch between the username and password field. Would be great to save time using tab to switch between input fields when entering credentials.

**Comment by flaviocopes** [comment]
It does for me! (when in the username field, I press tab, I'm sent to the password field). That is managed directly by the browser. Which browser are you using?

**Comment by kLOsk** [comment]
I'm using Chrome on Mac. Latest stable. I found the reason for my problem. It is because of the Dashlane plugin, which triggers a password selector for my localhost env. Disabling that helps :)

**Comment by flaviocopes** [comment]
:+1:
