### ISSUE TITLE
Activation does not go to the login page

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-login#70]
Clicking the activation link goes to the front page.
It should go to the login page so you can see the `User activated successfully` message and to login.

Under User Registration>Options, all options are checked except for `Login the user after registration`.

Also, I don't get the admin notification that a new user has registered.

Using `develop` and `Antimatter` theme.

**Comment by flaviocopes** [comment]
I added a new option to set the redirect after the activation. So in this case you can set a redirect after the registration (show a page wher eyou tell the user to activate, for example) and then you have a second redirect after the activation.

Emails should get to the store owner if you have "Send notification email" enabled, just tried.
