### ISSUE TITLE
Add flood protection for password reset request

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-login#76]
Currently, it is possible to bombard password reset requests. Please limit it to 1 per hour or a configurable time.

**Comment by vanjasiu** [comment]
Hello, i  implemented  discussed  here  enhancement. It  is  in  pull   https://github.com/getgrav/grav-plugin-login/pull/91

**Comment by rhukster** [comment]
I know this is long delayed, but i'm going to manually merge this with some additions tomorrow.

**Comment by rhukster** [comment]
Added, and also on login too.
