### ISSUE TITLE
Problem of redirect when the user error his password or username

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav-plugin-login#77]
If a page is locked and one user try to login and he err the access, the content of page is showed even so.
![err-login-showed-contet](https://cloud.githubusercontent.com/assets/3677780/15359684/69a2ba20-1cd8-11e6-8d22-be2b2139624f.PNG)

**Comment by Vivalldi** [comment]
@lauroguedes what version of the plugin are you using and theme if you wouldn't mind

**Comment by lauroguedes** [comment]
@Vivalldi I installed the grav and theme today. I made the configuration and saw the problem, so it is in the version the newest.

**Comment by flaviocopes** [comment]
Fixed in Login 2.0, available in Grav 1.1
