### ISSUE TITLE
RuntimeException Email not configured when registering

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-login#78]
Getting the `RuntimeException Email not configured` message when registering and email has not been configured.

**Comment by Vivalldi** [comment]
Try setting the config to not send email on user configuration.
```
user_registration:
  options:
    send_notification_email: false
```

**Comment by Quy** [comment]
OK, but it should display a pretty warning message like the Reset Password `Cannot reset password. This site is not configured to send emails`.

**Comment by flaviocopes** [comment]
You get a nice message if you have not enabled `system.errors.display`. 
Otherwise you're in debug mode and an exception is shown.

If you want to tweak the message shown you can do so by editing the plugin language file, or post a PR to change it globally if you think this is the case.

Closing.
