### ISSUE TITLE
`Validate double entered password` disabled not enforced

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-login#79]
`Validate double entered password` is disabled yet the register page has 2 password fields.

**Comment by flaviocopes** [comment]
The value is enabled by default and the default registration form asks for the password confirmation.
The form cannot be changed based on this setting.

If you want a single password field in the registration form, you need to have a custom registration form https://github.com/getgrav/grav-plugin-login#customizing-the-registration-form
