### ISSUE TITLE
Usernames containing dots

### ISSUE THREAD

**Issue by izzyu91** [getgrav/grav-plugin-login#81]
Is there a reason why dots are not allowed in usernames?

We use a schema of firstname.lastname throughout our systems to simplify authenticating.

**Comment by flaviocopes** [comment]
There's no "technical limitation". It's just a convention.

You can change the login format regex to suit your needs on a custom registration page (https://github.com/getgrav/grav-plugin-login#customizing-the-registration-form)

**Comment by izzyu91** [comment]
The login format regex on a registration page, yeah. But sorry I forgot to mention that we are not using a registration page. Just the admin panel and the cli to manage users.

**Comment by flaviocopes** [comment]
Ah yes for admin, it's not possible to be changed, at the moment.

**Comment by martinvonwittich** [comment]
More than 16 characters by default would be nice too; as martin.von.wittich, I feel kinda discriminated ;)

**Comment by flaviocopes** [comment]
There is no real reason to limit to 16, it's a convention. It's configurable if you create a custom registration page: https://github.com/getgrav/grav-plugin-login#customizing-the-registration-form and change the validation pattern to `pattern: '^[a-z0-9_-]{3,30}$'`, for example.

**Comment by rhukster** [comment]
This has now been moved into Grav system config.  You will be able to change the username regex in one place and it will be used in all forms/fields rather than requiring manual modification in multiple places (Next Grav + Form + Login releases).
