### ISSUE TITLE
Moving the /user/accounts to a path outside the webroot?

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav-plugin-login#84]
Is there a way to move the /user/accounts directory to another location outside the webroot for security reasons? I'm not seeing a config for that and it seems like user://accounts/ is being used a number of times in the code.

**Comment by flaviocopes** [comment]
Currently the accounts folder is a child of the user folder, so the only way is to move the whole user folder to another location. You can open this as a Grav issue, as it's not login plugin specific, if you'd like this to be changed.

**Comment by akoebbe** [comment]
But don't the user/plugins and user/themes need to be in the webroot for theme assets?

**Comment by akoebbe** [comment]
Actually it looks like there is a stream set up for accounts in system/config/streams.yaml, should the login plugin use that stream rather than user://accounts/?

**Comment by flaviocopes** [comment]
👍 merged PR
