### ISSUE TITLE
Add optional ability to automatically set page.visibility based on access

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-login#87]
Look into using `onPageProcessed` to set the page's menu visibility based on user access if logged in.

**Comment by rhukster** [comment]
This is possible in the soon to be released 2.5.0 version that has a new option: `dynamic_page_visibility: true`

**Comment by Flamenco** [comment]
soon to be released? 👀

Do you mean this:

<img width="646" alt="Screenshot 2023-03-01 at 5 42 59 PM" src="https://user-images.githubusercontent.com/819940/222283313-4aa8c244-9fca-41b7-8dda-2b746b65dafb.png">
