### ISSUE TITLE
Class 'Grav\Plugin\Login\Utils' not found

### ISSUE THREAD

**Issue by ChrisGitIt** [getgrav/grav-plugin-login#89]
Hi all,

i get the following error while register :

> Class 'Grav\Plugin\Login\Utils' not found

I think its because in /plugins/login/classes/Login.php there is 
> use Grav\Plugin\Login\Utils as LoginUtils;

but there is no file "Utils.php" ... maybe it should be:
> use Grav\Plugin\Email\Utils as LoginUtils;

Greetings,

Chris

Bye the way: Installed everything yesterday. Current Grav and Login Plugin.
Edit: Changed
> use Grav\Plugin\Login\Utils as LoginUtils;
to
> use Grav\Plugin\Email\Utils as LoginUtils;

and everything seems to work.

**Comment by rhukster** [comment]
Not sure how i missed this!

**Comment by rhukster** [comment]
Fixed in release 2.1.2.  Thanks!
