### ISSUE TITLE
Add CSS asset in template code instead

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-login#93]
It's cool that there's a setting to control whether `login.css` is included, but I'm wondering if it'd be possible to include the CSS file through the Twig templates instead. Maybe the setting could still be kept around, but that would automatically exclude the CSS unless the template that it concerns is deliberately included in the theme.

**Comment by rhukster** [comment]
It's really very hard to include via a twig partial, because those have to extend base or whatever the parent twig template is that defines the assets blocks.  Doing it via the plugin is safer and more reliable.

**Comment by fredrikekelund** [comment]
But `/templates/login.html.twig` does extend a base template right?

**Comment by rhukster** [comment]
Yes but you can override it. Or you might use a theme that doesn't have its base called base.html.twig.
