### ISSUE TITLE
Login / Locale / Languages

### ISSUE THREAD

**Issue by jraack** [getgrav/grav-plugin-login#98]
Dear all,

I have my website in two different languages.
Before you login you choose your language, it sets it's locale based on the url, /fr/home or en/home,
en/home is default, but when choosing fr/home and logging in, it redirect me back to en/home.
Somehow it is working on my localhost, but not on the dev server. 

Any ideas?
Thanks!

**Comment by flaviocopes** [comment]
I tried on a multilang site and normally it's redirecting to the correct language, just tested. As you mention it works locally but not on a remote server, so not sure what that might be caused by, doesn't look a config issue as that would fail on the local server too. 

Can you pm me your `user/` folder zipped at https://gitter.im/flaviocopes to see if I can replicate it locally?

**Comment by jraack** [comment]
Hi @flaviocopes ,

I see that it only happens in IE. 
Something to do with the /home link, when i click on a link (after login) that redirects me to /home, it is working, but when clicking on a link that redirects me to / without home, it brings me to the login form.

It is working on Chrome for instance.

best,
Joost

**Comment by jraack** [comment]
@flaviocopes 

I have tried to debug it, it seems IE is losing it's session.. sometimes it gives me the login page when i am successfully logged in.
It is working in chrome, firefox and safari. It is IE11 in win7 (tested on virtual machine)
Any ideas?
Cheers,
Joe

**Comment by flaviocopes** [comment]
Not sure why that happens, as the redirect is server-side, but will try to replicate.

**Comment by jraack** [comment]
Hi @flaviocopes 

Forget my issue, you can close it. I have did a clean install. And somehow my grav was behind, so tested it, i have tried to replicate it but it is working now. Thank you for your response!
Best

**Comment by Vivalldi** [comment]
Alright. Let us know if something comes up again.
