### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by antonio9357** [getgrav/grav-plugin-login#99]
Hi everybody,

I had a little problem on login, it happens sometimes only:

I type my username and password, and I get the error "Invalid security token" (or something like that). It happens 2-3 times after submit and then logs in normally.

I checked php logs and nothing, tried to empty cache and delete cookies, no success.
Obviously I have all necessary rights, login is true and admin super also.

This is definitely not a big deal but for some users could be difficult.

**Comment by flaviocopes** [comment]
Is this happening locally, and if so what is your local environment setup? Windows / Apache ?

Also, which browser are you using?

**Comment by ShtHappens796** [comment]
If you are using https try to enforce it with some rewrite rules on the .htaccess file.

**Comment by mahagr** [comment]
@antonio9357 If you've been away for a long time, login may fail because of your session has expired. The above message basically means that the session which was used to load the login page is no longer valid. Reloading page before login should always prevent the issue from happening.

**Comment by rhukster** [comment]
Please try with latest login version. Error messages should be more helpful.

**Comment by rhukster** [comment]
Closing due to lack of response...
